### PR TITLE
feat: circleci and semantic-release

### PR DESCRIPTION
**Pull request by devfreddy**
Prerequisites:

brew install gnu-sed (for search and replace)
brew install bash (for associative arrays on mac)
npm install -g json (to modify with package.json)

- Github Personal Access token with "public_repo" scope
- Snyk API Token
- CircleCI Personal API Token
- Demotron (or other account) API Key

Required setup items:

- [x] Add project to CircleCI

- [x] Configure advanced CircleCI settings - https://circleci.com/gh/newrelic/nr1-customer-journey/edit#advanced-settings
    - [x] Only build pull requests
    - [x] Build forked pull requests

- [x] Add branch protection for the master branch (even from administrators)

- [x] Turn off "Branch or Tag Creation" webhook event under the configured CircleCI webhook endpoint

- [x] Add a Deploy Key (w/write access) to github repo (public key) & CircleCI (private key)

- [x] Add Github Personal access token as `GITHUB_TOKEN` ENV variable. [Required by: Semantic-Release Github Plugin](https://github.com/semantic-release/github/blob/master/README.md#github-authentication)

- [x] Add Snyk token as `SNYK_TOKEN` ENV variable in CircleCI

- [x] Add an appropriate NR api key for use in deployment with the nr1 cli as `NR1CLI_PROFILE_DEMOTRONV2` ENV variable in CircleCI

- [x] Copy .circleci directory. Note - there are some scripts used to copy this from `open-source-tools/nerdpacks/oss-template`, then search/replace the following strings:
    - NERDPACK_UUID
    - NERDPACK_SLUG
    - REPO_DEPLOY_KEY_FINGERPRINT

- [x] Import bot user's into CLA assistant

### CODE REVIEW

**Comment by devfreddy** [comment]
Ignoring job-lint failure until we do a second pass on repos with our [@newrelic/eslint-plugin-newrelic](https://github.com/newrelic/eslint-plugin-newrelic)

**Comment by eric-spence-code** [comment]
These changes look good to me. Any reason not to merge?

**Comment by ericSpence** [comment]
These changes look good to me. I say merge it

**Comment by devfreddy** [comment]
@ericSpence Working through a last bug or two exposed by merging a similar set of changes into other Nerdpacks. I'll update and merge soon. Thanks!

**Pull request merged**
