### PR TITLE
Add support for status io provider

### PR DESCRIPTION
**Pull request by tschmidtnimble**
Added support for the status io provider based on the ezidebit example.
https://ezidebit.status.io/

status.io works a little differently requiring a token

https://github.com/newrelic/nr1-status-pages/issues/6

### CODE REVIEW

**Comment by tschmidtnimble** [comment]
@devfreddy ?

**Comment by devfreddy** [comment]
@tschmidtnimble Apologies, we've been traveling a bit lately and still getting caught up.

Can you make two small adjustments for me in `package.json`?

1. Revert the UUID back to the original - it's a UUID we utilize when deploying to our demo environment.
2. Revert the version number back to `0.9` - it will get auto-incremented when I merge your changes to master.

Still looking, but this is fantastic, thanks for your contribution!

**Comment by tschmidtnimble** [comment]
Thanks @devfreddy . Requested changes have been made.

**Pull request merged**
